#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_call:

jobs:
  checks:
    name: Code checks
    runs-on: [self-hosted, ubuntu-22.04]
    steps:
      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup component add rustfmt clippy

      - name: Code format check
        run: cargo fmt --check

      - name: Clippy check
        run: cargo clippy --all-targets --all-feature -- --deny warnings

      - name: Build
        run: cargo build --release --all-targets

      - name: Run tests
        run: cargo test --release --verbose
        env:
          ASYNC_STD_THREAD_COUNT: 4
